remote_theme: jekyll/minima
markdown: GFM
google_analytics: G-XGVXNL7FMG
url: "https://wishlist.ph4r5h4d.me"
plugins:
  - jekyll-remote-theme
minima:
  social_links:
    twitter: ph4r5h4d
    github: ph4r5h4d
    instagram: farshadnematdoust
    linkedin: farshadnematdoust
    